tag_name:
  default: ""
  type: string
  description: "The stopwatch will appear in all topics with this tag"
button_spacing:
  default: 0.5
  type: float
  description: "Adjust the spacing between the clock and the control button (0.5 - 5.0)"
  min: 0.5
  max: 5.0
display_on_mobile:
  default: true
  type: bool
